context:
  version: "16.2.3"

package:
  name: turbopack-cli
  version: ${{ version }}

source:
  url: https://github.com/vercel/next.js/archive/v${{ version }}.tar.gz
  sha256: 5bb2b680595867fe37763689b1fa17ed60b799f4b4a42e5ad2cbf00ef8f35c69

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - turbopack-cli --help

about:
  license: MIT
  license_file:
    - license.md
    - THIRDPARTY.yml
  summary: CLI for turbopack
  homepage: https://github.com/vercel/next.js
  repository: https://github.com/vercel/next.js

extra:
  recipe-maintainers:
    - danielnachun
