context:
  version: "16.2.6"

package:
  name: turbopack-cli
  version: ${{ version }}

source:
  url: https://github.com/vercel/next.js/archive/v${{ version }}.tar.gz
  sha256: 119c7afb3f19bf3de81283d4fab6b318f3b9ba3113acda83aee0de181be68a85

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - turbopack-cli --help

about:
  license: MIT
  license_file:
    - license.md
    - THIRDPARTY.yml
  summary: CLI for turbopack
  homepage: https://github.com/vercel/next.js
  repository: https://github.com/vercel/next.js

extra:
  recipe-maintainers:
    - danielnachun
