context:
  version: "16.2.9"

package:
  name: turbopack-cli
  version: ${{ version }}

source:
  url: https://github.com/vercel/next.js/archive/v${{ version }}.tar.gz
  sha256: 62092e9a0f7ecd271ec4c4b94a1e8890cd33648df02bdc82946fe5b5bb47e086

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - turbopack-cli --help

about:
  license: MIT
  license_file:
    - license.md
    - THIRDPARTY.yml
  summary: CLI for turbopack
  homepage: https://github.com/vercel/next.js
  repository: https://github.com/vercel/next.js

extra:
  recipe-maintainers:
    - danielnachun
